name: Build Unsigned BitChat IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build BitChat archive (no signing)
        run: |
          xcodebuild clean archive \
            -scheme "bitchat (iOS)" \
            -project bitchat.xcodeproj \
            -destination "generic/platform=iOS" \
            -archivePath build/bitchat.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""

      - name: Manually package .ipa
        run: |
          mkdir -p Payload
          cp -r build/bitchat.xcarchive/Products/Applications/*.app Payload/
          zip -r BitChat.ipa Payload
          mkdir -p build/export
          mv BitChat.ipa build/export/

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: BitChat-IPA
          path: build/export/BitChat.ipa
